version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
  parameter-store:
    NUGET_API_KEY: NuGetAPIKey
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - dotnet restore
      - ./scripts/publish-package.sh