version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
  parameter-store:
    ROLE_ARN: NugetCrossAccountArn
    SECRET_ARN: SecretArnNuget
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - ./scripts/install-dotnet.sh
      - dotnet restore
      - ./scripts/publish-package.sh