version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
    ROLE_ARN: arn:aws:iam::582595803497:role/CloudWatch-Logs-EMF-build-role
  parameter-store:
    SECRET_ARN: SecretArnNuget
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      - ./scripts/install-dotnet.sh
      - dotnet restore
      - ./scripts/publish-package.sh