version: 0.2

env:
  variables:
    AWS_REGION: us-west-2
  parameter-store:
    NUGET_API_KEY: NuGetAPIKey
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  build:
    commands:
      # install the latest patch version of 3.1
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -c 3.1
      - dotnet --version
      - dotnet nuget help
      - dotnet restore
      - ./scripts/publish-package.sh